apiVersion: v1
kind: Secret
metadata:
  name: database-auth-secret
  {{ if not .Values.databaseConnection.password }}
  annotations:
    helm.sh/hook: pre-install
  {{ end }}

{{ if .Values.databaseConnection.password }}

stringData:
  password: {{ .Values.databaseConnection.password }}

{{ else }}

data:
  password: {{ randAlphaNum 32 | b64enc }}

{{ end }}
