apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: slurm
    app.kubernetes.io/component: login
  name: login
spec:
  ports:
    - name: ssh
      port: 22
      targetPort: 22
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: slurm
    app.kubernetes.io/component: login
    