{{ if .Values.database.enabled }}

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: slurm
    app.kubernetes.io/component: mysql
  name: {{ .Values.databaseConnection.hostname }}
spec:
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  selector:
    app.kubernetes.io/name: slurm
    app.kubernetes.io/component: mysql

{{ end }}
