apiVersion: batch/v1
kind: Job
metadata:
  name: pre-upgrade-hook
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 0
  template:
    metadata:
      name: pre-upgrade-hook
    spec:
      restartPolicy: Never
      containers:
      - name: pre-upgrade-hook
        image: {{ .Values.sdcImage }}
        args:
          - pre-upgrade-hook
        volumeMounts:
          - mountPath: /tempmounts/munge.key
            name: munge-key-secret
            subPath: munge.key
          - mountPath: /etc/slurm/slurm.conf
            name: slurm-config-volume
            subPath: slurm.conf
      volumes:
        - name: munge-key-secret
          secret:
            secretName: {{ .Values.secrets.mungeKey }}
        - name: slurm-config-volume
          configMap:
            name: {{ .Values.configmaps.slurmConf }}
      
