apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-generator-account
  annotations:
    "kubernetes.io/enforce-mountable-secrets": "true"
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
automountServiceAccountToken: True
secrets:
  - name: host-keys-secret
