apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: slurm
    app.kubernetes.io/component: slurmd
  name: {{ .Values.slurmd.name }}
spec:
  replicas: {{ .Values.slurmd.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: slurm
      app.kubernetes.io/component: slurmd
  serviceName: slurmd
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: slurm
        app.kubernetes.io/component: slurmd
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          whenUnsatisfiable: ScheduleAnyway
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: slurm
              app.kubernetes.io/component: slurmd
      containers:
        - args:
            - slurmd
            - -F
            - -vvv
          image: {{ .Values.slurmImage }}
          name: slurmd
          ports:
            - containerPort: 6818
          resources: {}
          volumeMounts:
            - mountPath: /etc/slurm/
              name: slurm-config-volume
            - mountPath: {{ .Values.storage.mountPath }}
              name: slurm-jobdir
            - mountPath: /tmp/munge.key
              name: munge-key-secret
              subPath: munge.key
          securityContext:
            privileged: true
      dnsConfig:
        searches:
          - slurmd.{{ .Release.Namespace }}.svc.cluster.local
      restartPolicy: Always
      volumes:
        - name: slurm-jobdir
          persistentVolumeClaim:
            claimName: {{ .Values.storage.claimName }}
        - name: slurm-config-volume
          configMap:
            name: {{ .Values.configmaps.slurmConf }}
        - name: munge-key-secret
          secret:
            secretName: {{ .Values.secrets.mungeKey }}
            defaultMode: 0400
