apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: slurm
    app.kubernetes.io/component: slurmd
  name: slurmd
spec:
  replicas: {{ .Values.replicas.slurmd }}
  selector:
    matchLabels:
      app.kubernetes.io/name: slurm
      app.kubernetes.io/component: slurmd
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: slurm
        app.kubernetes.io/component: slurmd
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          whenUnsatisfiable: ScheduleAnyway
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: slurm
              app.kubernetes.io/component: slurmd
      containers:
        - args:
            - slurmd
          image: {{ .Values.sdcImage }}
          name: slurmd
          ports:
            - containerPort: 6818
          resources: {}
          volumeMounts:
            - mountPath: /etc/slurm/slurm.conf
              name: slurm-config-volume
              subPath: slurm.conf
            - mountPath: {{ .Values.nfs.mountPath }}
              name: slurm-jobdir
            - mountPath: /tempmounts/munge.key
              name: munge-key-secret
              subPath: munge.key
          securityContext:
            capabilities:
              add:
                - SYS_RESOURCE
                - CHOWN
                - DAC_OVERRIDE
                - FOWNER
                - FSETID
                - KILL
                - SETGID
                - SETUID
                - SETPCAP
                - NET_BIND_SERVICE
                - NET_RAW
                - SYS_CHROOT
                - MKNOD
                - AUDIT_READ
                - AUDIT_WRITE
                - AUDIT_CONTROL
                - BLOCK_SUSPEND
                - BPF
                - SETFCAP
                - CHECKPOINT_RESTORE
                - DAC_READ_SEARCH
                - IP_LOCK
                - IPC_OWNER
                - LEASE
                - LINUX_IMMUTABLE
                - MAC_ADMIN
                - MAC_OVERRIDE
                - NET_ADMIN
                - NET_BROADCAST
                - PERFMON
                - SYS_ADMIN
                - SYS_BOOT
                - SYS_NICE
                - SYS_PACCT
                - SYS_PTRACE
                - SYS_RAWIO
                - SYS_TIME
                - SYS_TTY_CONFIG
                - SYSLOG
                - WAKE_ALARM
      restartPolicy: Always
      volumes:
        - name: slurm-jobdir
          nfs:
            server: {{ .Values.nfs.server }}
            path: {{ .Values.nfs.exportPath }}
        - name: slurm-config-volume
          configMap:
            name: {{ .Values.configmaps.slurmConf }}
        - name: munge-key-secret
          secret:
            secretName: {{ .Values.secrets.mungeKey }}
