apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: slurm
    app.kubernetes.io/component: slurmctld
  name: slurmctld-0
spec:
  ports:
    - name: slurmctld
      port: 6817
      targetPort: 6817
  selector:
    app.kubernetes.io/name: slurm
    app.kubernetes.io/component: slurmctld
