apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: slurm
    app.kubernetes.io/component: slurmdbd
  name: slurmdbd
spec:
  ports:
    - name: slurmdbd
      port: 6819
      targetPort: 6819
  selector:
    app.kubernetes.io/name: slurm
    app.kubernetes.io/component: slurmdbd
