apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: slurm
    app.kubernetes.io/component: slurmd
  name: slurmd
spec:
  ports:
    - name: "6818"
      port: 6818
      targetPort: 6818
    - name: "jupyter"
      port: 8888
      targetPort: 8888
  selector:
    app.kubernetes.io/name: slurm
    app.kubernetes.io/component: slurmd
  clusterIP: None
