apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: slurm
    app.kubernetes.io/component: slurmdbd
  name: slurmdbd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: slurm
      app.kubernetes.io/component: slurmdbd
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: slurm
        app.kubernetes.io/component: slurmdbd
    spec:
      containers:
        - args:
            - slurmdbd
            - -vvv
          image: {{ .Values.slurmImage }}
          name: slurmdbd
          ports:
            - containerPort: 6819
          resources: {}
          volumeMounts:
            - mountPath: /etc/slurm/slurm.conf
              name: slurm-config-volume
              subPath: slurm.conf
            - mountPath: /tmp/munge.key
              name: munge-key-secret
              subPath: munge.key
            - mountPath: /tmp/slurmdbd.conf
              name: dbd-config-volume
              subPath: slurmdbd.conf
          env:
            - name: StoragePass
              valueFrom:
                secretKeyRef:
                  name: database-auth-secret
                  key: password
      hostname: slurmdbd
      restartPolicy: Always
      volumes:
        - name: dbd-config-volume
          configMap:
            name: {{ .Values.configmaps.slurmdbdConf }}
        - name: slurm-config-volume
          configMap:
            name: {{ .Values.configmaps.slurmConf }}
        - name: munge-key-secret
          secret:
            secretName: {{ .Values.secrets.mungeKey }}
            defaultMode: 0400
