apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: slurm
    app.kubernetes.io/component: slurmctld
  name: {{ .Values.slurmctld.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: slurm
      app.kubernetes.io/component: slurmctld
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: slurm
        app.kubernetes.io/component: slurmctld
    spec:
      containers:
        - args:
            - slurmctld
            - -vvv
          image: {{ .Values.slurmImage }}
          name: slurmctld
          ports:
            - containerPort: 6817
          resources: {}
          volumeMounts:
            - mountPath: {{ .Values.storage.mountPath }}
              name: slurm-jobdir
            - mountPath: /etc/slurm/
              name: slurm-config-volume
            - mountPath: /tmp/munge.key
              name: munge-key-secret
              subPath: munge.key
            - mountPath: /var/spool/slurmctld
              name: slurmctld-state
      dnsConfig:
        searches:
          - slurmd.{{ .Release.Namespace }}.svc.cluster.local
      restartPolicy: Always
      volumes:
        - name: slurm-jobdir
          persistentVolumeClaim:
            claimName: {{ .Values.storage.claimName }}
        - name: slurmctld-state
          persistentVolumeClaim:
            claimName: var-spool-slurmctld
        - name: slurm-config-volume
          configMap:
            name: {{ .Values.configmaps.slurmConf }}
        - name: munge-key-secret
          secret:
            secretName: {{ .Values.secrets.mungeKey }}
            defaultMode: 0400
