apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: slurm
    app.kubernetes.io/component: slurmctld
  name: slurmctld
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: slurm
      app.kubernetes.io/component: slurmctld
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: slurm
        app.kubernetes.io/component: slurmctld
    spec:
      containers:
        - args:
            - slurmctld
            - -vvvvv
          image: {{ .Values.slurmImage }}
          name: slurmctld
          ports:
            - containerPort: 6817
          resources: {}
          volumeMounts:
            - mountPath: {{ .Values.nfs.mountPath }}
              name: slurm-jobdir
            - mountPath: /etc/slurm/
              name: slurm-config-volume
            - mountPath: /tmp/munge.key
              name: munge-key-secret
              subPath: munge.key
            - mountPath: /var/spool/slurmctld
              name: slurmctld-state
            - mountPath: /tmp/kubeconfig
              name: kubeconfig-secret
              subPath: kubeconfig
      dnsConfig:
        searches:
          - slurmd.default.svc.cluster.local
      restartPolicy: Always
      volumes:
        - name: slurm-jobdir
          persistentVolumeClaim:
            claimName: {{ .Values.nfs.claimName }}
        - name: slurmctld-state
          persistentVolumeClaim:
            claimName: var-spool-slurmctld
        - name: slurm-config-volume
          projected:
            sources:
              - configMap:
                  name: {{ .Values.configmaps.slurmConf }}
              - configMap:
                  name: slurmd-pod-template
        - name: munge-key-secret
          secret:
            secretName: {{ .Values.secrets.mungeKey }}
            defaultMode: 0400
        - name: kubeconfig-secret
          secret:
            secretName: kubeconfig-secret
            defaultMode: 0400
