apiVersion: v1
kind: ConfigMap
metadata:
  name: slurmd-pod-template
data:
  slurmd-pod-template.yml: |
    apiVersion: v1
    kind: Pod
    metadata:
      labels:
        app.kubernetes.io/name: slurm
        app.kubernetes.io/component: slurmd
      name: SLURMD_NODENAME # Irrelevant for DNS but must be be currently-unique so using slurmd name is convenient
    spec:
      # topologySpreadConstraints:
      #   - maxSkew: 1
      #     whenUnsatisfiable: ScheduleAnyway
      #     topologyKey: kubernetes.io/hostname
      #     labelSelector:
      #       matchLabels:
      #         app.kubernetes.io/name: slurm
      #         app.kubernetes.io/component: slurmd
      hostname: SLURMD_NODENAME # required to create DNS records for pod
      subdomain: slurmd # has to match name of headless service to create DNS records for pod
      containers:
        - args:
            - slurmd
            - -b
            - -vvvvv
            - -N
            - SLURMD_NODENAME
          image: {{ .Values.slurmImage }}
          name: slurmd
          ports:
            - containerPort: 6818
          resources: {}
          volumeMounts:
            - mountPath: /etc/slurm/
              name: slurm-config-volume
            - mountPath: {{ .Values.nfs.mountPath }}
              name: slurm-jobdir
            - mountPath: /tmp/munge.key
              name: munge-key-secret
              subPath: munge.key
          securityContext:
            privileged: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      dnsConfig:
        searches:
          - slurmd.default.svc.cluster.local
      restartPolicy: Always
      volumes:
        - name: slurm-jobdir
          persistentVolumeClaim:
            claimName: {{ .Values.nfs.claimName }}
        - name: slurm-config-volume
          configMap:
            name: {{ .Values.configmaps.slurmConf }}
        - name: munge-key-secret
          secret:
            secretName: {{ .Values.secrets.mungeKey }}
            defaultMode: 0400
