apiVersion: batch/v1
kind: Job
metadata:
  name: undrain-nodes-hook
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 0
  template:
    metadata:
      name: undrain-nodes-hook
    spec:
      restartPolicy: Never
      containers:
      - name: undrain-nodes-hook
        image: {{ .Values.slurmImage }}
        args:
          - undrain-nodes-hook
        volumeMounts:
          - mountPath: /tmp/munge.key
            name: munge-key-secret
            subPath: munge.key
          - mountPath: /etc/slurm/
            name: slurm-config-volume
      volumes:
        - name: munge-key-secret
          secret:
            secretName: {{ .Values.secrets.mungeKey }}
            defaultMode: 0400
        - name: slurm-config-volume
          configMap:
            name: {{ .Values.configmaps.slurmConf }}
