slurmImage: ghcr.io/stackhpc/slurm-docker-cluster:7f4d64e

login:
  # Deployment resource name
  name: login
  replicas: 1

slurmd:
  # StatefulSet resource name
  name: slurmd
  replicas: 2

slurmctld:
  # StatefulSet resource name
  name: slurmctld
  # NOTE: We don't include a replicas field here because
  # replicas > 1 for slurmctld needs extra Slurm config

storage:
  mountPath: /home
  # The name of a Read-Write-Many StorageClass to use for
  # the persistent volume which is shared across Slurm nodes
  # Note: If using the default value then you must set
  # rooknfs.enabled = true below to ensure that Rook NFS is 
  # installed on the cluster as a dependency of this Slurm
  # chart. If you are using a separate RWM StorageClass, then
  # set rooknfs.enabled = false
  storageClassName: &storageclassname slurm-rook-nfs
  # Name for the R-W-M volume to provision
  claimName: slurm-shared-storage
  # Capacite of the R-W-M volume
  capacity: &capacity 10Gi


# Values to be passed to the rook-nfs sub-chart
# See rook-nfs sub-chart for full set of available config values
rooknfs:
  enabled: true
  storageClassName: *storageclassname
  # Name for the NFSServer resource created by Rook
  serverName: rook-nfs
  # Capacity for the backing Read-Write-*Once* volume 
  # than Rook will create to provide the actual storage to 
  # the NFS server. Since we're using the Rook NFS in a 
  # slightly unconventional way here, we just want to anchor
  # this value to the requested storage capacity for the RWM
  # volume specified in storage.capacity
  storageCapacity: *capacity


sqlImage: mariadb:10.10

databaseStorage: 100Mi

configmaps:
  authorizedKeys: authorized-keys-configmap
  slurmConf: slurm-conf-configmap
  slurmdbdConf: slurmdbd-conf-configmap
  sshdConfig: sshd-config-configmap

secrets:
  databaseAuth: database-auth-secret
  mungeKey: munge-key-secret
  