sdcImage: ghcr.io/stackhpc/slurm-docker-cluster:c0b2f69

replicas:
  slurmd: 2
  login: 1

nfs:
  mountPath: /home
  claimName: rook-nfs-pv-claim

sqlImage: mariadb:10.10

databaseStorage: 100Mi

configmaps:
  authorizedKeys: authorized-keys-configmap
  slurmConf: slurm-conf-configmap
  slurmdbdConf: slurmdbd-conf-configmap
  sshdConfig: sshd-config-configmap

secrets:
  databaseAuth: database-auth-secret
  mungeKey: munge-key-secret
  
jupyterApp:
  repoURL: "https://github.com/stackhpc/OOD-containerised-jupyter.git"
  repoTag: "v0.1"