name: Publish charts
# Run the tasks on every push
on: push
jobs:
  publish_charts:
    name: Build and push Helm charts
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          # This is important for the semver action to work correctly
          # when determining the number of commits since the last tag
          fetch-depth: 0
          submodules: true

      - name: Get SemVer version for current commit
        id: semver
        uses: stackhpc/github-actions/semver@master

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        with:
          ## limits ssh access and adds the ssh public keys of the listed GitHub users
          limit-access-to-users: wtripp180901,sd109

      - name: Publish Helm charts
        uses: stackhpc/github-actions/helm-publish@test/capture-stderr
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ steps.semver.outputs.version }}
          app-version: ${{ steps.semver.outputs.short-sha }}
